### ISSUE TITLE
Automate release procedure

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#1088]
To follow the release-often model we need to automate most of the release procedures. Current tasks in order are:

### Stage 1

- [x] request Weblate to push everything
- [x] pull & create release branch
- [x] update version code and name
- [x] build APKs
- update CHANGELOG.md **(needs human intervention)**
- update English store listings **(needs human intervention)**

### Stage 2

- [x] update Google Play translations (`app/src/main/play/update.sh`) (pulling at this point makes little sense since very little time has passed)
- [x] commit, push
- [x] create release tag
- [x] upload APKs to kontalk.org/files (release script)
- [x] create release draft on GitHub, attaching APKs **(needs human intervention... does it?)**

### CI take over

- [x] Travis publishes to Google Play alpha (ensure store listings is updated)
- promote to production (should be done manually for now, just to be safe)

### External tasks

- [ ] update F-Droid metadata (should be done automatically by F-Droid build server, [however it is not](https://gitlab.com/fdroid/fdroiddata/merge_requests/2618#note_45622656))
- Weblate: move Google Play and Amazon store listings to new release branch (no API available, **needs human intervention**, however it can be done separately)
- publish announcement on forum **(needs human intervention)**

---

#### GitHub Release creation

Based on a template, we could ask the user to input just the incipit of the release text or let him fill in the missing parts of the template.

**Comment by daniele-athome** [comment]
All done, expect F-Droid metadata update which requires a whole other procedure.
[Release checklist](https://github.com/kontalk/androidclient/wiki/Release-checklist) was updated too.
